<a href="https://colab.research.google.com/github/yashMaheshBangera/large-behavior-model-twin2k/blob/main/notebooks/01_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exploratory Data Analysis (EDA)

In [1]:
from datasets import load_dataset

In [2]:
fp_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","full_persona")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.0k [00:00<?, ?B/s]

full_persona/chunks/persona_chunk_001.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_001.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_002.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_002.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_003.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_003.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_004.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_004.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_005.pa(…): reconstructing file:   0%|          |  0.00B / 29.1MB

full_persona/chunks/persona_chunk_005.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_006.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_006.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_007.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_007.pa(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [3]:
ws_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","wave_split")

wave_split/chunks/wave_persona_chunk_001(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_001(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_002(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_002(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_003(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_003(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_004(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_004(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_005(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_005(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_006(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_006(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_007(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_007(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [4]:
fp_data["data"]["pid"]

Column(['574', '2001', '1710', '1277', '789', ...])

In [5]:
ws_data

DatasetDict({
    data: Dataset({
        features: ['pid', 'wave1_3_persona_text', 'wave1_3_persona_json', 'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
        num_rows: 2058
    })
})

In [6]:
fp_df = fp_data["data"].to_pandas()
ws_df = ws_data["data"].to_pandas()

In [7]:
fp_df.columns

Index(['pid', 'persona_text', 'persona_summary', 'persona_json'], dtype='object')

In [8]:
ws_df.columns

Index(['pid', 'wave1_3_persona_text', 'wave1_3_persona_json',
       'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
      dtype='object')

In [9]:
# Checking if there are duplicate p_id values
fp_n_unique_pid = fp_df.pid.nunique()
if (fp_n_unique_pid==len(fp_df)):
  print("For full_persona : No duplicate p_id values found.")
else:
  print("For full_persona : Duplicate p_id values found!")
ws_n_unique_pid = ws_df.pid.nunique()
if (ws_n_unique_pid==len(ws_df)):
  print("For wave_split : No duplicate p_id values found.")
else:
  print("For wave_split : Duplicate p_id values found!")

For full_persona : No duplicate p_id values found.
For wave_split : No duplicate p_id values found.

In [10]:
import json

In [11]:
def check_unique_list(df,block_names,count):
  fp_persona_sample = json.loads(df["persona_json"][count])
  current_block_names = []
  for i in fp_persona_sample:
    current_block_names.append(i["BlockName"])
  return current_block_names

In [12]:
block_names = []
for count in range(0,len(fp_df),1):
  current_block_names = check_unique_list(fp_df,block_names,count)
  block_names.append(current_block_names)

In [13]:
#Checking the length of each unique block name
count_arr = []
for i in range(len(block_names)):
  count_arr.append(len(block_names[i]))
unique_flag = set(count_arr)
print(unique_flag)

{30, 31}

In [14]:
print("Number of times 31 count array appears : " + str(count_arr.count(30)))
print("Number of times 32 count array appears : " + str(count_arr.count(31)))

Number of times 31 count array appears : 6
Number of times 32 count array appears : 2052

In [15]:
#Getting indices which are missing the last row
indices_31 = []
for i in range(len(count_arr)):
  if count_arr[i]==30:
    indices_31.append(i)

In [16]:
indices_31

[156, 395, 421, 686, 796, 941]

In [17]:
#Parse the data
import pandas as pd

In [18]:
def parse_extract_questions(df):
  num_rows = len(df)
  parsed_questions = []
  for i in range(0,num_rows,1):
    current_pid = df["pid"].iloc[i]
    current_persona = df["persona_json"].iloc[i]
    current_persona = json.loads(current_persona)
    current_persona_df = pd.DataFrame(current_persona)
    len_current_persona_df = len(current_persona_df)
    wave = 1
    for j in range(0,len_current_persona_df,1):
      current_question = current_persona_df["Questions"].iloc[j]
      name = current_persona_df["BlockName"].iloc[j].strip()
      if name == "Personality" and j > 1:    # 2nd and 3rd Personality blocks
          wave += 1
      if name == "False consensus":
          wave = 4
      for k in range(0,len(current_question),1):
        q = current_persona_df["Questions"].iloc[j][k]
        current_dictionary = {
            "pid":current_pid,
            "element":j,
            "block_name":name,
            "block_type":current_persona_df["BlockType"].iloc[j],
            "wave":wave,
            "qID":q["QuestionID"],
            "qtext":q["QuestionText"],
            "qtype":q["QuestionType"],
            "options":q.get("Options"),
            "settings_selector":q.get("Settings",{}).get("Selector"),
            "settings_subSelector":q.get("Settings",{}).get("SubSelector"),
            "settings_forceResponse":q.get("Settings",{}).get("ForceResponse"),
            "answers_selected_position":q.get("Answers",{}).get("SelectedByPosition"),
            "answers_selected_text":q.get("Answers",{}).get("SelectedText")
        }
        parsed_questions.append(current_dictionary)
  return pd.DataFrame(parsed_questions)

In [19]:
parsed_questions_df = parse_extract_questions(fp_df)

In [20]:
parsed_questions_df.shape

(485641, 14)

In [21]:
block_n = (
    parsed_questions_df.groupby(["wave", "block_name"])["pid"]
    .nunique()
    .reset_index(name="n_block")
)

In [22]:
block_n

    wave                                       block_name  n_block
0      1                                  Cognitive tests     2058
1      1                                     Demographics     2058
2      1                             Economic preferences     2058
3      1                     Economic preferences - intro     2058
4      1                                      Personality     2058
5      2                                  Cognitive tests     2058
6      2                             Economic preferences     2058
7      2                     Economic preferences - intro     2058
8      2                                     Forward Flow     2053
9      2                                      Personality     2058
10     3                                  Cognitive tests     2057
11     3                             Economic preferences     2058
12     3                                      Personality     2058
13     4               Absolute vs. relative - calculator     1031
14     4                   Absolute vs. relative - jacket     1027
15     4                                    Allais Form 1     1051
16     4                                    Allais Form 2     1007
17     4               Anchoring - African countries high     1056
18     4                Anchoring - African countries low     1002
19     4                         Anchoring - redwood high     1009
20     4                          Anchoring - redwood low     1049
21     4                           Base-rate 30 engineers     1043
22     4                           Base-rate 70 engineers     1015
23     4                                   Disease - gain     1003
24     4                                     Disease-loss     1055
25     4                                  False consensus     2058
26     4                            Less is More Gamble A      735
27     4                            Less is More Gamble B      672
28     4                            Less is More Gamble C      651
29     4                            Linda -no conjunction     1029
30     4                                Linda-conjunction     1029
31     4                                      Myside Ford     1015
32     4                                    Myside German     1043
33     4           Non-experimental heuristics and biases     2058
34     4                           Outcome bias - failure     1006
35     4                           Outcome bias - success     1052
36     4  Probability matching vs. maximizing - Problem 1     1032
37     4  Probability matching vs. maximizing - Problem 2     1026
38     4                    Product Preferences - Pricing     2058
39     4                          Proportion dominance 1A      735
40     4                          Proportion dominance 1B      672
41     4                          Proportion dominance 1C      651
42     4                          Proportion dominance 2A      735
43     4                          Proportion dominance 2B      672
44     4                          Proportion dominance 2C      651
45     4                                   Sunk cost - no     1035
46     4                                  Sunk cost - yes     1023
47     4                WTA/WTP Thaler - WTP noncertainty      673
48     4           WTA/WTP Thaler problem - WTA certainty      673
49     4           WTA/WTP Thaler problem - WTP certainty      712

In [23]:
num_questions = []
#For each of the 2058 persons
for i in range(0,len(fp_df),1):
  current_persona_questions = json.loads(fp_df["persona_json"].iloc[i])
  #Goes from 0 to 30/31
  count=0
  for j in range(0,len(current_persona_questions),1):
    count+=len(current_persona_questions[j]["Questions"])
  num_questions.append(count)

In [24]:
pd.Series(num_questions).value_counts()

236    2019
235      31
234       8
Name: count, dtype: int64

In [25]:
q_n = (
    parsed_questions_df.groupby(["wave", "block_name", "qID"])["pid"]
    .nunique()
    .reset_index(name="n_question")
)

In [26]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [27]:
parsed_questions_df['qID'].nunique()

246

In [28]:
q_n = (
    parsed_questions_df.groupby(["wave", "block_name", "qID"])["pid"]
    .nunique()
    .reset_index(name="n_question")
)

In [29]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [30]:
dup_ids = q_n.loc[q_n.duplicated("qID", keep=False), "qID"].unique()

duplicate_qIDs = (
    parsed_questions_df[parsed_questions_df["qID"].isin(dup_ids)]
    .drop_duplicates(["wave", "block_name", "qID"])
    [["wave", "block_name", "qID", "qtype", "qtext"]]
    .sort_values(["qID", "wave"])
    .reset_index(drop=True)
)
duplicate_qIDs

,wave,block_name,qID,qtype,qtext
0,1,Cognitive tests,QID241,DB,"In this section, you will answer a series of 4..."
1,2,Cognitive tests,QID241,DB,You are now going to answer 20 questions that ...
2,1,Cognitive tests,QID268,MC,"If a glock is not a XAR, you can say:"
3,2,Personality,QID268,TE,In this task we would like you to write about ...
4,1,Cognitive tests,QID269,MC,"If a koy is a YOF, you can say:"
5,2,Personality,QID269,TE,2. Please describe the type of person you ough...
6,1,Cognitive tests,QID270,MC,"If a koy is not a YOF, you can say:"
7,2,Personality,QID270,TE,3. Please describe the type of person you actu...
8,1,Cognitive tests,QID271,MC,Premise 1: All animals love water. Premise 2: ...
9,2,Economic preferences,QID271,TE,We are now interested in what you were thinkin...
10,1,Cognitive tests,QID272,MC,Premise 1: All animals with four legs are dang...
11,2,Economic preferences,QID272,TE,"Second, please list the thoughts you had when ..."
12,1,Cognitive tests,QID275,MC,Premise 1: All mammals swim. Premise 2: Whales...
13,3,Economic preferences,QID275,TE,We are now interested in what you were thinkin...
14,1,Cognitive tests,QID276,MC,Premise 1: All unemployed people are poor. Pre...
15,2,Economic preferences,QID276,Matrix,"In this question, the LOTTERY is a 50% chance ..."
16,1,Cognitive tests,QID277,MC,Premise I: All things that have a motor need o...
17,2,Economic preferences,QID277,Matrix,"In this question, the LOTTERY is a 50% chance ..."
18,1,Cognitive tests,QID278,MC,Suppose that it is true that: All the XAR's ar...
19,2,Economic preferences,QID278,Matrix,"In this question, the LOTTERY is a 50% chance ..."
20,1,Cognitive tests,QID279,MC,You are now going to receive a series of eight...
21,2,Economic preferences,QID279,Matrix,"In this question, the LOTTERY is a 50% chance ..."

In [31]:
q_n[q_n.duplicated("qID", keep=False)].sort_values(["qID", "wave"])

     wave            block_name     qID  n_question
2       1       Cognitive tests  QID241        2058
86      2       Cognitive tests  QID241        2058
4       1       Cognitive tests  QID268        2058
130     2           Personality  QID268        2058
5       1       Cognitive tests  QID269        2058
131     2           Personality  QID269        2058
6       1       Cognitive tests  QID270        2058
133     2           Personality  QID270        2058
7       1       Cognitive tests  QID271        2058
119     2  Economic preferences  QID271        2054
8       1       Cognitive tests  QID272        2058
120     2  Economic preferences  QID272        2028
11      1       Cognitive tests  QID275        2058
138     3  Economic preferences  QID275        2058
12      1       Cognitive tests  QID276        2058
121     2  Economic preferences  QID276        2058
13      1       Cognitive tests  QID277        2058
122     2  Economic preferences  QID277        2058
14      1       Cognitive tests  QID278        2058
123     2  Economic preferences  QID278        2058
15      1       Cognitive tests  QID279        2058
124     2  Economic preferences  QID279        2058

In [32]:
parsed_questions_df["q_key"] = "W" + parsed_questions_df["wave"].astype(str) + "_" + parsed_questions_df["qID"]

In [33]:
parsed_questions_df["q_key"]

0           W1_QID11
1           W1_QID12
2           W1_QID13
3           W1_QID14
4           W1_QID15
             ...
485636    W4_QID9_36
485637    W4_QID9_37
485638    W4_QID9_38
485639    W4_QID9_39
485640    W4_QID9_40
Name: q_key, Length: 485641, dtype: object

In [34]:
block_n = (
    parsed_questions_df.groupby(["wave", "block_name"])["pid"]
    .nunique()
    .reset_index(name="n_block")
)

In [35]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [36]:
block_n

    wave                                       block_name  n_block
0      1                                  Cognitive tests     2058
1      1                                     Demographics     2058
2      1                             Economic preferences     2058
3      1                     Economic preferences - intro     2058
4      1                                      Personality     2058
5      2                                  Cognitive tests     2058
6      2                             Economic preferences     2058
7      2                     Economic preferences - intro     2058
8      2                                     Forward Flow     2053
9      2                                      Personality     2058
10     3                                  Cognitive tests     2057
11     3                             Economic preferences     2058
12     3                                      Personality     2058
13     4               Absolute vs. relative - calculator     1031
14     4                   Absolute vs. relative - jacket     1027
15     4                                    Allais Form 1     1051
16     4                                    Allais Form 2     1007
17     4               Anchoring - African countries high     1056
18     4                Anchoring - African countries low     1002
19     4                         Anchoring - redwood high     1009
20     4                          Anchoring - redwood low     1049
21     4                           Base-rate 30 engineers     1043
22     4                           Base-rate 70 engineers     1015
23     4                                   Disease - gain     1003
24     4                                     Disease-loss     1055
25     4                                  False consensus     2058
26     4                            Less is More Gamble A      735
27     4                            Less is More Gamble B      672
28     4                            Less is More Gamble C      651
29     4                            Linda -no conjunction     1029
30     4                                Linda-conjunction     1029
31     4                                      Myside Ford     1015
32     4                                    Myside German     1043
33     4           Non-experimental heuristics and biases     2058
34     4                           Outcome bias - failure     1006
35     4                           Outcome bias - success     1052
36     4  Probability matching vs. maximizing - Problem 1     1032
37     4  Probability matching vs. maximizing - Problem 2     1026
38     4                    Product Preferences - Pricing     2058
39     4                          Proportion dominance 1A      735
40     4                          Proportion dominance 1B      672
41     4                          Proportion dominance 1C      651
42     4                          Proportion dominance 2A      735
43     4                          Proportion dominance 2B      672
44     4                          Proportion dominance 2C      651
45     4                                   Sunk cost - no     1035
46     4                                  Sunk cost - yes     1023
47     4                WTA/WTP Thaler - WTP noncertainty      673
48     4           WTA/WTP Thaler problem - WTA certainty      673
49     4           WTA/WTP Thaler problem - WTP certainty      712

In [37]:
coverage = q_n.merge(block_n, on=["wave", "block_name"], how="left")
coverage["n_missing"] = coverage["n_block"] - coverage["n_question"]
coverage[coverage["n_missing"] > 0]

     wave            block_name     qID  n_question  n_block  n_missing
16      1       Cognitive tests   QID52        2057     2058          1
20      1       Cognitive tests   QID56        2057     2058          1
89      2       Cognitive tests   QID38        2055     2058          3
92      2       Cognitive tests   QID41        2056     2058          2
119     2  Economic preferences  QID271        2054     2058          4
120     2  Economic preferences  QID272        2028     2058         30

In [38]:
for key in ["W1_QID56", "W2_QID38", "W2_QID41"]:
    sub = parsed_questions_df[parsed_questions_df["q_key"] == key]
    print("====", key)
    print(sub["qtext"].iloc[0][:300])          # the question, first 300 characters
    print(sub["answers_selected_text"].value_counts(dropna=False))
    print()

==== W1_QID56
Please indicate which is the best answer to solve the puzzle below.

Puzzle Grid (3x3 Matrix)

Each cell in a 3x3 matrix contains a circle with an arrow pointing in one of four directions (up, down, left, right) and sometimes includes a diagonal or horizontal/vertical line inside the circle. We'll
answers_selected_text
D    1468
A     255
B     176
E     118
C      22
F      18
Name: count, dtype: int64

==== W2_QID38
Normally, which asset described below displays the highest fluctuations over time?
answers_selected_text
Stocks             1897
Bonds                62
Do not know          61
Savings account      35
Name: count, dtype: int64

==== W2_QID41
Considering a long time period (for example 10 or 20 years), which asset described below normally gives the highest return?
answers_selected_text
Stocks             1221
Bonds               570
Do not know         140
Savings account     125
Name: count, dtype: int64

In [39]:
db_questions = (parsed_questions_df[parsed_questions_df["qtype"] == "DB"]
   .drop_duplicates("q_key")
   [["wave", "block_name", "q_key", "qtext"]]
   .sort_values(["wave", "block_name"])
   .reset_index(drop=True))

In [40]:
missing_qIDs = coverage[coverage["n_missing"] > 0]

In [41]:
parsed_questions_df.columns

Index(['pid', 'element', 'block_name', 'block_type', 'wave', 'qID', 'qtext',
       'qtype', 'options', 'settings_selector', 'settings_subSelector',
       'settings_forceResponse', 'answers_selected_position',
       'answers_selected_text', 'q_key'],
      dtype='object')

In [42]:
off_forceResponse_df = parsed_questions_df[parsed_questions_df["settings_forceResponse"]=="OFF"]

In [43]:
off_forceResponse_df

,pid,element,block_name,block_type,wave,qID,qtext,qtype,options,settings_selector,settings_subSelector,settings_forceResponse,answers_selected_position,answers_selected_text,q_key
17,574,1,Personality,Standard,1,QID29,Below are 24 different values that people rate...,Matrix,None,Likert,SingleAnswer,OFF,"[5, 5, 6, 7, 8, 9, 9, 9, 8, 8, 8, 7, 5, 6, 9, ...","[Quite Important to me 5, Quite Important to m...",W1_QID29
27,574,2,Cognitive tests,Standard,1,QID56,Please indicate which is the best answer to so...,MC,"[A, B, C, D, E, F]",SAHR,TX,OFF,4,D,W1_QID56
93,574,6,Cognitive tests,Standard,2,QID38,"Normally, which asset described below displays...",MC,"[Savings account, Stocks, Bonds, Do not know]",SAVR,TX,OFF,2,Stocks,W2_QID38
95,574,6,Cognitive tests,Standard,2,QID40,When an investor spreads their money among dif...,MC,"[Increases, Decreases, Stays the same, Do not ...",SAVR,TX,OFF,2,Decreases,W2_QID40
96,574,6,Cognitive tests,Standard,2,QID41,Considering a long time period (for example 10...,MC,"[Savings account, Stocks, Bonds, Do not know]",SAVR,TX,OFF,2,Stocks,W2_QID41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485539,1029,9,Economic preferences,Standard,2,QID271,We are now interested in what you were thinkin...,TE,None,FORM,None,OFF,None,None,W2_QID271
485540,1029,9,Economic preferences,Standard,2,QID272,"Second, please list the thoughts you had when ...",TE,None,FORM,None,OFF,None,None,W2_QID272
485541,1029,10,Personality,Standard,3,QID28,Here are a number of characteristics that may ...,Matrix,None,Likert,SingleAnswer,OFF,"[7, 6, 6, 7, 6, 4, 6, 4, 4, 2]","[Definitely true, True, True, Definitely true,...",W3_QID28
485574,1029,11,Cognitive tests,Standard,3,QID221,Imagine you see a number of cards from a set o...,MC,"[A, F, 3, 7]",MAHR,TX,OFF,"[1, 3]","[A, 3]",W3_QID221
485576,1029,12,Economic preferences,Standard,3,QID275,We are now interested in what you were thinkin...,TE,None,FORM,None,OFF,None,None,W3_QID275

In [44]:
coverage["q_key"] = "W" + coverage["wave"].astype(str) + "_" + coverage["qID"]
missing_keys = coverage.loc[coverage["n_missing"] > 0, "q_key"]

In [45]:
missing_keys

16      W1_QID52
20      W1_QID56
89      W2_QID38
92      W2_QID41
119    W2_QID271
120    W2_QID272
Name: q_key, dtype: object

In [46]:
coverage_with_off_forceResponse = off_forceResponse_df[off_forceResponse_df["q_key"].isin(missing_keys)]

In [47]:
coverage_with_off_forceResponse["q_key"].value_counts()

q_key
W1_QID56     2057
W2_QID41     2056
W2_QID38     2055
W2_QID271    2054
W2_QID272    2028
Name: count, dtype: int64

In [48]:
parsed_questions_df["is_answerable"] = parsed_questions_df["qtype"] != "DB"

In [49]:
non_answerable_df = parsed_questions_df[parsed_questions_df["qtype"] == "DB"]

In [50]:
non_answerable_df["q_key"].value_counts()

q_key
W1_QID260    2058
W1_QID262    2058
W1_QID241    2058
W1_QID62     2058
W1_QID73     2058
W1_QID265    2058
W1_QID266    2058
W2_QID285    2058
W2_QID241    2058
W2_QID242    2058
W2_QID243    2058
W2_QID249    2058
W3_QID127    2058
W3_QID240    2058
W4_QID8      2058
Name: count, dtype: int64

In [56]:
parsed_questions_df.columns

Index(['pid', 'element', 'block_name', 'block_type', 'wave', 'qID', 'qtext',
       'qtype', 'options', 'settings_selector', 'settings_subSelector',
       'settings_forceResponse', 'answers_selected_position',
       'answers_selected_text', 'q_key', 'is_answerable'],
      dtype='object')

In [66]:
answers_selected_df = parsed_questions_df[["qtype","settings_selector"]]

In [72]:
answers_selected_df["qtype"].unique()

array(['MC', 'DB', 'Matrix', 'TE', 'Slider'], dtype=object)

In [73]:
(parsed_questions_df.drop_duplicates("q_key")
   .groupby(["qtype", "settings_selector"], dropna=False)
   .size())

qtype   settings_selector
DB      NaN                   15
MC      MAHR                   1
        MAVR                  20
        SAHR                  25
        SAVR                 129
Matrix  Bipolar               13
        Likert                23
Slider  HSLIDER                3
TE      FORM                   4
        ML                     3
        SL                    21
dtype: int64

In [74]:
def extract_raw_answers(df):
    rows = []
    for pid, pj in zip(df["pid"], df["persona_json"]):
        persona = json.loads(pj)
        for element, block in enumerate(persona):
            for q in block.get("Questions", []):
                rows.append({
                    "pid": pid,
                    "element": element,
                    "qID": q["QuestionID"],
                    "answers_raw": q.get("Answers"),
                })
    return pd.DataFrame(rows)

raw_df = extract_raw_answers(fp_df)

In [75]:
raw_df

,pid,element,qID,answers_raw
0,574,0,QID11,"{'SelectedByPosition': 3, 'SelectedText': 'Sou..."
1,574,0,QID12,"{'SelectedByPosition': 1, 'SelectedText': 'Male'}"
2,574,0,QID13,"{'SelectedByPosition': 1, 'SelectedText': '18-..."
3,574,0,QID14,"{'SelectedByPosition': 3, 'SelectedText': 'Som..."
4,574,0,QID15,"{'SelectedByPosition': 1, 'SelectedText': 'Whi..."
...,...,...,...,...
485636,1029,30,QID9_36,"{'SelectedByPosition': 1, 'SelectedText': 'Yes..."
485637,1029,30,QID9_37,"{'SelectedByPosition': 1, 'SelectedText': 'Yes..."
485638,1029,30,QID9_38,"{'SelectedByPosition': 2, 'SelectedText': 'No,..."
485639,1029,30,QID9_39,"{'SelectedByPosition': 1, 'SelectedText': 'Yes..."
485640,1029,30,QID9_40,"{'SelectedByPosition': 1, 'SelectedText': 'Yes..."

In [76]:
before = len(parsed_questions_df)

parsed_questions_df = parsed_questions_df.merge(
    raw_df, on=["pid", "element", "qID"], how="left"
)

print(before, len(parsed_questions_df))                 # must be equal
print(parsed_questions_df["answers_raw"].isna().sum())  # rows with no Answers

485641 485641
30870

In [77]:
(parsed_questions_df["answers_raw"].isna() == ~parsed_questions_df["is_answerable"]).all()

np.True_

In [78]:
answerable = parsed_questions_df[parsed_questions_df["is_answerable"]]

for (qtype, sel), group in answerable.groupby(["qtype", "settings_selector"]):
    example = group.iloc[0]
    print(f"--- {qtype} / {sel}  ({example['q_key']})")
    print(example["answers_raw"])
    print()

--- MC / MAHR  (W3_QID221)
{'SelectedByPosition': [1], 'SelectedText': ['A']}

--- MC / MAVR  (W3_QID126)
{'SelectedByPosition': [1], 'SelectedText': ["I don't feel sad"]}

--- MC / SAHR  (W1_QID56)
{'SelectedByPosition': 4, 'SelectedText': 'D'}

--- MC / SAVR  (W1_QID11)
{'SelectedByPosition': 3, 'SelectedText': 'South (TX, OK, AR, LA, KY, TN, MS, AL, WV, DC, MD, DE, VA, NC, SC, GA, FL)'}

--- Matrix / Bipolar  (W2_QID84)
{'SelectedByPosition': [1, 1, 1, 1, 1, 1, 1, 2, 2], 'SelectedText': ['1', '1', '1', '1', '1', '1', '1', '2', '2']}

--- Matrix / Likert  (W1_QID25)
{'SelectedByPosition': [4, 2, 5, 1, 4, 4, 4, 3, 4, 4, 4, 2, 5, 4, 4, 3, 4, 1, 2, 4, 3, 4, 1, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 5, 2, 4, 2, 5, 4, 4, 5, 5, 4, 5], 'SelectedText': ['Agree a little', 'Disagree a little', 'Agree strongly', 'Disagree strongly', 'Agree a little', 'Agree a little', 'Agree a little', 'Neither agree nor disagree', 'Agree a little', 'Agree a little', 'Agree a little', 'Disagree a little', 'Agree strongly', 'Agree a little', 'Agree a little', 'Neither agree nor disagree', 'Agree a little', 'Disagree strongly', 'Disagree a little', 'Agree a little', 'Neither agree nor disagree', 'Agree a little', 'Disagree strongly', 'Disagree a little', 'Agree a little', 'Agree a little', 'Disagree a little', 'Disagree a little', 'Disagree a little', 'Disagree a little', 'Disagree a little', 'Agree a little', 'Agree a little', 'Agree strongly', 'Disagree a little', 'Agree a little', 'Disagree a little', 'Agree strongly', 'Agree a little', 'Agree a little', 'Agree strongly', 'Agree strongly', 'Agree a little', 'Agree strongly']}

--- Slider / HSLIDER  (W4_QID156)
{'Values': ['87']}

--- TE / FORM  (W2_QID10)
{'Text': [{'word 1': 'bear'}, {'word 2': 'deer'}, {'word 3': 'turkey'}, {'word 4': 'squirrel'}, {'word 5': 'racoon'}, {'word 6': 'skunk'}, {'word 7': 'groundhog'}, {'word 8': 'woods'}, {'word 9': 'outside'}, {'word 10': 'leaves'}, {'word 11': 'trees'}, {'word 12': 'camping'}, {'word 13': 'hiking'}, {'word 14': 'backpacking'}, {'word 15': 'walking'}, {'word 16': 'nature'}, {'word 17': 'biking'}, {'word 18': 'tires'}, {'word 19': 'peddels'}, {'word 20': 'fun'}]}

--- TE / ML  (W2_QID268)
{'Text': 'I aspire to be hardworking and successful. I aspire to be caring and kind. I aspire to take care of others. '}

--- TE / SL  (W1_QID52)
{'Text': 'Emily'}

In [82]:
#Checking the keys for matrix answer types

In [83]:
persona = json.loads(fp_df["persona_json"].iloc[0])
matrix_q = next(q for b in persona for q in b["Questions"] if q["QuestionType"] == "Matrix")
print(matrix_q.keys())

dict_keys(['QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'Columns', 'Settings', 'Answers'])

In [85]:
from collections import Counter

key_sets = Counter()
for pj in fp_df["persona_json"]:
    for b in json.loads(pj):
        for q in b["Questions"]:
            if q["QuestionType"] == "Matrix":
                sel = q.get("Settings", {}).get("Selector")
                key_sets[(sel, tuple(sorted(q.keys())))] += 1

for (sel, keys), n in key_sets.items():
    print(sel, n, keys)

Likert 34986 ('Answers', 'Columns', 'QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'Settings')
Bipolar 12348 ('Answers', 'Columns', 'QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'RowsID', 'Settings')
Bipolar 14406 ('Answers', 'Columns', 'QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'Settings')
Likert 6174 ('Answers', 'Columns', 'QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'RowsID', 'Settings')
Likert 2058 ('Answers', 'Columns', 'ColumnsID', 'QuestionID', 'QuestionText', 'QuestionType', 'Rows', 'Settings')

In [92]:
from collections import defaultdict

versions = defaultdict(set)
for pj in fp_df["persona_json"]:
    for element, b in enumerate(json.loads(pj)):
        for q in b["Questions"]:
            if q["QuestionType"] == "Matrix":
                definition = (
                    tuple(q["Rows"]),
                    tuple(q["Columns"]),
                    tuple(q.get("RowsID", [])),
                    tuple(q.get("ColumnsID", [])),
                )
                versions[(b["BlockName"].strip(), q["QuestionID"])].add(definition)

{k: len(v) for k, v in versions.items() if len(v) > 1}

{}

In [94]:
shown = set()
for b in json.loads(fp_df["persona_json"].iloc[0]):
    for q in b["Questions"]:
        if q["QuestionType"] == "Matrix":
            for extra in ["RowsID", "ColumnsID"]:
                if extra in q and extra not in shown:
                    shown.add(extra)
                    print("====", extra, q["QuestionID"])
                    print("Rows:     ", q["Rows"][:5])
                    print("Columns:  ", q["Columns"])
                    print(extra + ":", q[extra])
                    print("Answers:  ", q["Answers"]["SelectedByPosition"][:5])
                    print()

==== RowsID QID84
Rows:      ['$6.00 in 6 weeks:$3.00 in 5 weeks', '$6.00 in 6 weeks:$4.00 in 5 weeks', '$6.00 in 6 weeks:$4.50 in 5 weeks', '$6.00 in 6 weeks:$5.00 in 5 weeks', '$6.00 in 6 weeks:$5.25 in 5 weeks']
Columns:   ['1', '2']
RowsID: ['4', '5', '6', '7', '8', '9', '10', '11', '12']
Answers:   [1, 1, 1, 1, 1]

==== ColumnsID QID236
Rows:      ['In social situations, I have the ability to alter my behavior if I feel that something else is called for.', 'I have the ability to control the way I come across to people, depending on the impression I wish to give them.', "When I feel that the image I am portraying isn't working, I can readily change it to something that does.", 'I have trouble changing my behavior to suit different people and different situations.', 'I have found that I can adjust my behavior to meet the requirements of any situation I find myself in.']
Columns:   ['Certainly, always false', 'Generally false', 'Somewhat false, but with exceptions', 'Somewhat true, but with exceptions', 'Generally true', 'Certainly, always true']
ColumnsID: ['1', '2', '3', '4', '5', '10']
Answers:   [4, 4, 4, 3, 5]

In [87]:
parsed_questions_df.loc[parsed_questions_df["qID"] == "QID236", "q_key"].unique()

array(['W3_QID236'], dtype=object)

In [88]:
mtx = parsed_questions_df[parsed_questions_df["q_key"] == "W3_QID236"]
mtx["answers_raw"].apply(lambda a: max(a["SelectedByPosition"])).max()

6

In [90]:
rows_id_info = {}
for b in json.loads(fp_df["persona_json"].iloc[0]):
    for q in b["Questions"]:
        if q["QuestionType"] == "Matrix" and "RowsID" in q:
            ids = [int(x) for x in q["RowsID"]]
            rows_id_info[q["QuestionID"]] = {
                "n_rows": len(q["Rows"]),
                "n_ids": len(ids),
                "ascending": ids == sorted(ids),
            }
pd.DataFrame(rows_id_info).T

       n_rows n_ids ascending
QID84       9     9      True
QID244     10    10      True
QID245     11    11      True
QID246      9     9      True
QID247     10    10      True
QID248     11    11      True
QID234     12    12     False
QID238     15    15      True
QID287     10    10      True

In [91]:
for b in json.loads(fp_df["persona_json"].iloc[0]):
    for q in b["Questions"]:
        if q["QuestionID"] == "QID234":
            for rid, row in zip(q["RowsID"], q["Rows"]):
                print(rid, "|", row[:80])
            print(q["Columns"])
            print(q["Answers"]["SelectedByPosition"])

1 | I often combine possessions in such a way that I create a personal image that ca
2 | I often try to find a more interesting version of run-of-the-mill products becau
3 | I actively seek to develop my personal uniqueness by buying special products or
4 | Having an eye for products that are interesting and unusual assists me in establ
5 | When it comes to the products I buy and the situations in which I use them, I ha
6 | I have often violated the understood rules of my social group regarding what to
7 | I have often gone against the understood rules of my social group regarding when
12 | I enjoy challenging the prevailing taste of people I know by buying something th
8 | When a product I own becomes popular among the general population, I begin to us
9 | I often try to avoid products or brands that I know are bought by the general po
10 | As a rule, I dislike products or brands that are customarily bought by everyone.
11 | The more commonplace a product or brand is among the general population, the les
['Disagree strongly', 'Disagree a little', 'Neither agree nor disagree', 'Agree a little', 'Agree strongly']
[4, 4, 3, 4, 2, 2, 2, 3, 2, 2, 2, 2]

In [89]:
bad = Counter()
for pj in fp_df["persona_json"]:
    for b in json.loads(pj):
        for q in b["Questions"]:
            if q["QuestionType"] == "Matrix":
                n_cols = len(q["Columns"])
                for pos in q["Answers"]["SelectedByPosition"]:
                    if not (1 <= pos <= n_cols):
                        bad[q["QuestionID"]] += 1
print(bad)

Counter()

In [95]:
mismatches = 0
for pj in fp_df["persona_json"]:
    for b in json.loads(pj):
        for q in b["Questions"]:
            if q["QuestionType"] == "Matrix":
                if len(q["Rows"]) != len(q["Answers"]["SelectedByPosition"]):
                    mismatches += 1
print(mismatches)

74

In [97]:
mismatch_rows = []
for pid, pj in zip(fp_df["pid"], fp_df["persona_json"]):
    for element, b in enumerate(json.loads(pj)):
        for q in b["Questions"]:
            if q["QuestionType"] == "Matrix":
                n_rows = len(q["Rows"])
                n_ans = len(q["Answers"]["SelectedByPosition"])
                if n_rows != n_ans:
                    mismatch_rows.append({
                        "pid": pid,
                        "block_name": b["BlockName"].strip(),
                        "qID": q["QuestionID"],
                        "n_rows": n_rows,
                        "n_answers": n_ans,
                    })

mm = pd.DataFrame(mismatch_rows)
mm.groupby(["block_name", "qID", "n_rows", "n_answers"]).size()

block_name   qID    n_rows  n_answers
Personality  QID28  10      9            16
             QID29  24      12            2
                            17            1
                            18            6
                            19            1
                            21            1
                            22            3
                            23           44
dtype: int64

In [98]:
for qid in ["QID28", "QID29"]:
    ex = mm[mm["qID"] == qid].iloc[0]
    persona = json.loads(fp_df.loc[fp_df["pid"] == ex["pid"], "persona_json"].iloc[0])
    for element, b in enumerate(persona):
        for q in b["Questions"]:
            if q["QuestionID"] == qid and b["BlockName"].strip() == "Personality":
                print("====", qid, "element", element, "pid", ex["pid"])
                print("Settings:", q["Settings"])
                print("Answer keys:", list(q["Answers"].keys()))
                print("Rows:", len(q["Rows"]), "| Answers:", len(q["Answers"]["SelectedByPosition"]))
                print(q["Answers"])
                print()

==== QID28 element 10 pid 896
Settings: {'Selector': 'Likert', 'SubSelector': 'SingleAnswer', 'ForceResponse': 'OFF'}
Answer keys: ['SelectedByPosition', 'SelectedText']
Rows: 10 | Answers: 9
{'SelectedByPosition': [6, 5, 6, 6, 6, 6, 6, 6, 6], 'SelectedText': ['True', 'Probably true', 'True', 'True', 'True', 'True', 'True', 'True', 'True']}

==== QID29 element 1 pid 169
Settings: {'Selector': 'Likert', 'SubSelector': 'SingleAnswer', 'ForceResponse': 'OFF'}
Answer keys: ['SelectedByPosition', 'SelectedText']
Rows: 24 | Answers: 23
{'SelectedByPosition': [4, 7, 5, 8, 9, 8, 7, 6, 4, 9, 5, 4, 7, 6, 9, 8, 3, 9, 6, 8, 4, 3, 2], 'SelectedText': ['4', '7', 'Quite Important to me 5', '8', 'Highly Important to me 9', '8', '7', '6', '4', 'Highly Important to me 9', 'Quite Important to me 5', '4', '7', '6', 'Highly Important to me 9', '8', '3', 'Highly Important to me 9', '6', '8', '4', '3', '2']}

In [99]:
def extract_matrix_answers(df):
    rows = []
    for pid, pj in zip(df["pid"], df["persona_json"]):
        for element, block in enumerate(json.loads(pj)):
            for q in block.get("Questions", []):
                if q["QuestionType"] != "Matrix":
                    continue
                positions = q["Answers"]["SelectedByPosition"]
                texts = q["Answers"]["SelectedText"]
                if len(positions) != len(q["Rows"]):
                    continue        # rows skipped: alignment unknown, so leave out
                for i, (row_text, pos, txt) in enumerate(zip(q["Rows"], positions, texts), start=1):
                    rows.append({
                        "pid": pid,
                        "element": element,
                        "qID": q["QuestionID"],
                        "sub_item": i,
                        "sub_item_text": row_text,
                        "answer_pos": pos,
                        "answer_text": txt,
                        "n_scale": len(q["Columns"]),
                    })
    return pd.DataFrame(rows)

matrix_df = extract_matrix_answers(fp_df)

In [100]:
matrix_df = matrix_df.merge(
    parsed_questions_df[["pid", "element", "qID", "wave", "block_name", "q_key"]].drop_duplicates(),
    on=["pid", "element", "qID"], how="left",
)

In [101]:
print(len(matrix_df))
print(matrix_df["q_key"].isna().sum())               # should be 0: every row matched
matrix_df.groupby("q_key")["sub_item"].max()         # statements per question

897806
0

q_key
W1_QID232    20
W1_QID235     6
W1_QID25     44
W1_QID26     18
W1_QID29     24
W1_QID35     12
W2_QID125    21
W2_QID233    16
W2_QID244    10
W2_QID245    11
W2_QID246     9
W2_QID247    10
W2_QID248    11
W2_QID250    14
W2_QID251    14
W2_QID252    14
W2_QID27     13
W2_QID276    14
W2_QID277    14
W2_QID278    14
W2_QID279    14
W2_QID30      8
W2_QID84      9
W3_QID234    12
W3_QID236    13
W3_QID237    12
W3_QID238    15
W3_QID239     6
W3_QID28     10
W4_QID159     3
W4_QID160     3
W4_QID198    10
W4_QID203     6
W4_QID287    10
W4_QID288     4
W4_QID289     4
Name: sub_item, dtype: int64

In [102]:
skipped = matrix_df[matrix_df["qID"].isin(["QID28", "QID29"])]
skipped.groupby("q_key")["pid"].nunique()

q_key
W1_QID29    2000
W3_QID28    2042
Name: pid, dtype: int64

In [103]:
matrix_df[matrix_df["q_key"].isin(["W1_QID29", "W3_QID28"])].groupby("q_key")["pid"].nunique()

q_key
W1_QID29    2000
W3_QID28    2042
Name: pid, dtype: int64

In [104]:
(matrix_df["answer_pos"] > matrix_df["n_scale"]).sum(), (matrix_df["answer_pos"] < 1).sum()

(np.int64(0), np.int64(0))