<a href="https://colab.research.google.com/github/yashMaheshBangera/large-behavior-model-twin2k/blob/main/notebooks/01_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exploratory Data Analysis (EDA)

In [2]:
from datasets import load_dataset

In [3]:
fp_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","full_persona")

README.md:   0%|          | 0.00/11.0k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

full_persona/chunks/persona_chunk_001.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_001.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_002.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_002.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_003.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_003.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_004.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_004.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_005.pa(…): reconstructing file:   0%|          |  0.00B / 29.1MB

full_persona/chunks/persona_chunk_005.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_006.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_006.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_007.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_007.pa(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [4]:
ws_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","wave_split")

wave_split/chunks/wave_persona_chunk_001(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_001(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_002(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_002(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_003(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_003(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_004(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_004(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_005(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_005(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_006(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_006(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_007(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_007(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [5]:
fp_data["data"]["pid"]

Column(['574', '2001', '1710', '1277', '789', ...])

In [6]:
ws_data

DatasetDict({
    data: Dataset({
        features: ['pid', 'wave1_3_persona_text', 'wave1_3_persona_json', 'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
        num_rows: 2058
    })
})

In [7]:
fp_df = fp_data["data"].to_pandas()
ws_df = ws_data["data"].to_pandas()

In [8]:
fp_df.columns

Index(['pid', 'persona_text', 'persona_summary', 'persona_json'], dtype='object')

In [9]:
ws_df.columns

Index(['pid', 'wave1_3_persona_text', 'wave1_3_persona_json',
       'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
      dtype='object')

In [10]:
# Checking if there are duplicate p_id values
fp_n_unique_pid = fp_df.pid.nunique()
if (fp_n_unique_pid==len(fp_df)):
  print("For full_persona : No duplicate p_id values found.")
else:
  print("For full_persona : Duplicate p_id values found!")
ws_n_unique_pid = ws_df.pid.nunique()
if (ws_n_unique_pid==len(ws_df)):
  print("For wave_split : No duplicate p_id values found.")
else:
  print("For wave_split : Duplicate p_id values found!")

For full_persona : No duplicate p_id values found.
For wave_split : No duplicate p_id values found.

In [11]:
import json

In [12]:
def check_unique_list(df,block_names,count):
  fp_persona_sample = json.loads(df["persona_json"][count])
  current_block_names = []
  for i in fp_persona_sample:
    current_block_names.append(i["BlockName"])
  return current_block_names

In [13]:
block_names = []
for count in range(0,len(fp_df),1):
  current_block_names = check_unique_list(fp_df,block_names,count)
  block_names.append(current_block_names)

In [16]:
#Checking the length of each unique block name
count_arr = []
for i in range(len(block_names)):
  count_arr.append(len(block_names[i]))
unique_flag = set(count_arr)
print(unique_flag)

{30, 31}

In [17]:
print("Number of times 31 count array appears : " + str(count_arr.count(30)))
print("Number of times 32 count array appears : " + str(count_arr.count(31)))

Number of times 31 count array appears : 6
Number of times 32 count array appears : 2052

In [18]:
#Getting indices which are missing the last row
indices_31 = []
for i in range(len(count_arr)):
  if count_arr[i]==30:
    indices_31.append(i)

In [19]:
indices_31

[156, 395, 421, 686, 796, 941]

In [22]:
#Parse the data
import pandas as pd

In [23]:
def parse_extract_questions(df):
  num_rows = len(df)
  parsed_questions = []
  for i in range(0,num_rows,1):
    current_pid = df["pid"].iloc[i]
    current_persona = df["persona_json"].iloc[i]
    current_persona = json.loads(current_persona)
    current_persona_df = pd.DataFrame(current_persona)
    len_current_persona_df = len(current_persona_df)
    wave = 1
    for j in range(0,len_current_persona_df,1):
      current_question = current_persona_df["Questions"].iloc[j]
      name = current_persona_df["BlockName"].iloc[j].strip()
      if name == "Personality" and j > 1:    # 2nd and 3rd Personality blocks
          wave += 1
      if name == "False consensus":
          wave = 4
      for k in range(0,len(current_question),1):
        q = current_persona_df["Questions"].iloc[j][k]
        current_dictionary = {
            "pid":current_pid,
            "element":j,
            "block_name":name,
            "block_type":current_persona_df["BlockType"].iloc[j],
            "wave":wave,
            "qID":q["QuestionID"],
            "qtext":q["QuestionText"],
            "qtype":q["QuestionType"],
            "options":q.get("Options"),
            "settings_selector":q.get("Settings",{}).get("Selector"),
            "settings_subSelector":q.get("Settings",{}).get("SubSelector"),
            "settings_forceResponse":q.get("Settings",{}).get("ForceResponse"),
            "answers_selected_position":q.get("Answers",{}).get("SelectedByPosition"),
            "answers_selected_text":q.get("Answers",{}).get("SelectedText")
        }
        parsed_questions.append(current_dictionary)
  return pd.DataFrame(parsed_questions)

In [24]:
parsed_questions_df = parse_extract_questions(fp_df)

In [60]:
parsed_questions_df.shape

(485641, 16)

In [25]:
block_n = (
    parsed_questions_df.groupby(["wave", "block_name"])["pid"]
    .nunique()
    .reset_index(name="n_block")
)

In [26]:
block_n

    wave                                       block_name  n_block
0      1                                  Cognitive tests     2058
1      1                                     Demographics     2058
2      1                             Economic preferences     2058
3      1                     Economic preferences - intro     2058
4      1                                      Personality     2058
5      2                                  Cognitive tests     2058
6      2                             Economic preferences     2058
7      2                     Economic preferences - intro     2058
8      2                                     Forward Flow     2053
9      2                                      Personality     2058
10     3                                  Cognitive tests     2057
11     3                             Economic preferences     2058
12     3                                      Personality     2058
13     4               Absolute vs. relative - calculator     1031
14     4                   Absolute vs. relative - jacket     1027
15     4                                    Allais Form 1     1051
16     4                                    Allais Form 2     1007
17     4               Anchoring - African countries high     1056
18     4                Anchoring - African countries low     1002
19     4                         Anchoring - redwood high     1009
20     4                          Anchoring - redwood low     1049
21     4                           Base-rate 30 engineers     1043
22     4                           Base-rate 70 engineers     1015
23     4                                   Disease - gain     1003
24     4                                     Disease-loss     1055
25     4                                  False consensus     2058
26     4                            Less is More Gamble A      735
27     4                            Less is More Gamble B      672
28     4                            Less is More Gamble C      651
29     4                            Linda -no conjunction     1029
30     4                                Linda-conjunction     1029
31     4                                      Myside Ford     1015
32     4                                    Myside German     1043
33     4           Non-experimental heuristics and biases     2058
34     4                           Outcome bias - failure     1006
35     4                           Outcome bias - success     1052
36     4  Probability matching vs. maximizing - Problem 1     1032
37     4  Probability matching vs. maximizing - Problem 2     1026
38     4                    Product Preferences - Pricing     2058
39     4                          Proportion dominance 1A      735
40     4                          Proportion dominance 1B      672
41     4                          Proportion dominance 1C      651
42     4                          Proportion dominance 2A      735
43     4                          Proportion dominance 2B      672
44     4                          Proportion dominance 2C      651
45     4                                   Sunk cost - no     1035
46     4                                  Sunk cost - yes     1023
47     4                WTA/WTP Thaler - WTP noncertainty      673
48     4           WTA/WTP Thaler problem - WTA certainty      673
49     4           WTA/WTP Thaler problem - WTP certainty      712

In [108]:
num_questions = []
#For each of the 2058 persons
for i in range(0,len(fp_df),1):
  current_persona_questions = json.loads(fp_df["persona_json"].iloc[i])
  #Goes from 0 to 30/31
  count=0
  for j in range(0,len(current_persona_questions),1):
    count+=len(current_persona_questions[j]["Questions"])
  num_questions.append(count)

In [112]:
pd.Series(num_questions).value_counts()

236    2019
235      31
234       8
Name: count, dtype: int64

In [109]:
q_n = (
    parsed_questions_df.groupby(["wave", "block_name", "qID"])["pid"]
    .nunique()
    .reset_index(name="n_question")
)

In [113]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [28]:
parsed_questions_df['qID'].nunique()

246

In [120]:
q_n = (
    parsed_questions_df.groupby(["wave", "block_name", "qID"])["pid"]
    .nunique()
    .reset_index(name="n_question")
)

In [123]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [134]:
dup_ids = q_n.loc[q_n.duplicated("qID", keep=False), "qID"].unique()

duplicate_qIDs = (
    parsed_questions_df[parsed_questions_df["qID"].isin(dup_ids)]
    .drop_duplicates(["wave", "block_name", "qID"])
    [["wave", "block_name", "qID", "qtype", "qtext"]]
    .sort_values(["qID", "wave"])
    .reset_index(drop=True)
)
duplicate_qIDs

,wave,block_name,qID,qtype,qtext
0,1,Cognitive tests,QID241,DB,"In this section, you will answer a series of 4..."
1,2,Cognitive tests,QID241,DB,You are now going to answer 20 questions that ...
2,1,Cognitive tests,QID268,MC,"If a glock is not a XAR, you can say:"
3,2,Personality,QID268,TE,In this task we would like you to write about ...
4,1,Cognitive tests,QID269,MC,"If a koy is a YOF, you can say:"
5,2,Personality,QID269,TE,2. Please describe the type of person you ough...
6,1,Cognitive tests,QID270,MC,"If a koy is not a YOF, you can say:"
7,2,Personality,QID270,TE,3. Please describe the type of person you actu...
8,1,Cognitive tests,QID271,MC,Premise 1: All animals love water. Premise 2: ...
9,2,Economic preferences,QID271,TE,We are now interested in what you were thinkin...
10,1,Cognitive tests,QID272,MC,Premise 1: All animals with four legs are dang...
11,2,Economic preferences,QID272,TE,"Second, please list the thoughts you had when ..."
12,1,Cognitive tests,QID275,MC,Premise 1: All mammals swim. Premise 2: Whales...
13,3,Economic preferences,QID275,TE,We are now interested in what you were thinkin...
14,1,Cognitive tests,QID276,MC,Premise 1: All unemployed people are poor. Pre...
15,2,Economic preferences,QID276,Matrix,"In this question, the LOTTERY is a 50% chance ..."
16,1,Cognitive tests,QID277,MC,Premise I: All things that have a motor need o...
17,2,Economic preferences,QID277,Matrix,"In this question, the LOTTERY is a 50% chance ..."
18,1,Cognitive tests,QID278,MC,Suppose that it is true that: All the XAR's ar...
19,2,Economic preferences,QID278,Matrix,"In this question, the LOTTERY is a 50% chance ..."
20,1,Cognitive tests,QID279,MC,You are now going to receive a series of eight...
21,2,Economic preferences,QID279,Matrix,"In this question, the LOTTERY is a 50% chance ..."

In [140]:
q_n[q_n.duplicated("qID", keep=False)].sort_values(["qID", "wave"])

     wave            block_name     qID  n_question
2       1       Cognitive tests  QID241        2058
86      2       Cognitive tests  QID241        2058
4       1       Cognitive tests  QID268        2058
130     2           Personality  QID268        2058
5       1       Cognitive tests  QID269        2058
131     2           Personality  QID269        2058
6       1       Cognitive tests  QID270        2058
133     2           Personality  QID270        2058
7       1       Cognitive tests  QID271        2058
119     2  Economic preferences  QID271        2054
8       1       Cognitive tests  QID272        2058
120     2  Economic preferences  QID272        2028
11      1       Cognitive tests  QID275        2058
138     3  Economic preferences  QID275        2058
12      1       Cognitive tests  QID276        2058
121     2  Economic preferences  QID276        2058
13      1       Cognitive tests  QID277        2058
122     2  Economic preferences  QID277        2058
14      1       Cognitive tests  QID278        2058
123     2  Economic preferences  QID278        2058
15      1       Cognitive tests  QID279        2058
124     2  Economic preferences  QID279        2058

In [135]:
parsed_questions_df["q_key"] = "W" + parsed_questions_df["wave"].astype(str) + "_" + parsed_questions_df["qID"]

In [136]:
parsed_questions_df["q_key"]

0           W1_QID11
1           W1_QID12
2           W1_QID13
3           W1_QID14
4           W1_QID15
             ...
485636    W4_QID9_36
485637    W4_QID9_37
485638    W4_QID9_38
485639    W4_QID9_39
485640    W4_QID9_40
Name: q_key, Length: 485641, dtype: object

In [142]:
block_n = (
    parsed_questions_df.groupby(["wave", "block_name"])["pid"]
    .nunique()
    .reset_index(name="n_block")
)

In [145]:
q_n

     wave                              block_name     qID  n_question
0       1                         Cognitive tests  QID123        2058
1       1                         Cognitive tests  QID124        2058
2       1                         Cognitive tests  QID241        2058
3       1                         Cognitive tests  QID265        2058
4       1                         Cognitive tests  QID268        2058
..    ...                                     ...     ...         ...
252     4                          Sunk cost - no  QID181        1035
253     4                         Sunk cost - yes  QID182        1023
254     4       WTA/WTP Thaler - WTP noncertainty  QID191         673
255     4  WTA/WTP Thaler problem - WTA certainty  QID190         673
256     4  WTA/WTP Thaler problem - WTP certainty  QID189         712

[257 rows x 4 columns]

In [143]:
block_n

    wave                                       block_name  n_block
0      1                                  Cognitive tests     2058
1      1                                     Demographics     2058
2      1                             Economic preferences     2058
3      1                     Economic preferences - intro     2058
4      1                                      Personality     2058
5      2                                  Cognitive tests     2058
6      2                             Economic preferences     2058
7      2                     Economic preferences - intro     2058
8      2                                     Forward Flow     2053
9      2                                      Personality     2058
10     3                                  Cognitive tests     2057
11     3                             Economic preferences     2058
12     3                                      Personality     2058
13     4               Absolute vs. relative - calculator     1031
14     4                   Absolute vs. relative - jacket     1027
15     4                                    Allais Form 1     1051
16     4                                    Allais Form 2     1007
17     4               Anchoring - African countries high     1056
18     4                Anchoring - African countries low     1002
19     4                         Anchoring - redwood high     1009
20     4                          Anchoring - redwood low     1049
21     4                           Base-rate 30 engineers     1043
22     4                           Base-rate 70 engineers     1015
23     4                                   Disease - gain     1003
24     4                                     Disease-loss     1055
25     4                                  False consensus     2058
26     4                            Less is More Gamble A      735
27     4                            Less is More Gamble B      672
28     4                            Less is More Gamble C      651
29     4                            Linda -no conjunction     1029
30     4                                Linda-conjunction     1029
31     4                                      Myside Ford     1015
32     4                                    Myside German     1043
33     4           Non-experimental heuristics and biases     2058
34     4                           Outcome bias - failure     1006
35     4                           Outcome bias - success     1052
36     4  Probability matching vs. maximizing - Problem 1     1032
37     4  Probability matching vs. maximizing - Problem 2     1026
38     4                    Product Preferences - Pricing     2058
39     4                          Proportion dominance 1A      735
40     4                          Proportion dominance 1B      672
41     4                          Proportion dominance 1C      651
42     4                          Proportion dominance 2A      735
43     4                          Proportion dominance 2B      672
44     4                          Proportion dominance 2C      651
45     4                                   Sunk cost - no     1035
46     4                                  Sunk cost - yes     1023
47     4                WTA/WTP Thaler - WTP noncertainty      673
48     4           WTA/WTP Thaler problem - WTA certainty      673
49     4           WTA/WTP Thaler problem - WTP certainty      712

In [147]:
coverage = q_n.merge(block_n, on=["wave", "block_name"], how="left")
coverage["n_missing"] = coverage["n_block"] - coverage["n_question"]
coverage[coverage["n_missing"] > 0]

     wave            block_name     qID  n_question  n_block  n_missing
16      1       Cognitive tests   QID52        2057     2058          1
20      1       Cognitive tests   QID56        2057     2058          1
89      2       Cognitive tests   QID38        2055     2058          3
92      2       Cognitive tests   QID41        2056     2058          2
119     2  Economic preferences  QID271        2054     2058          4
120     2  Economic preferences  QID272        2028     2058         30

In [151]:
for key in ["W1_QID56", "W2_QID38", "W2_QID41"]:
    sub = parsed_questions_df[parsed_questions_df["q_key"] == key]
    print("====", key)
    print(sub["qtext"].iloc[0][:300])          # the question, first 300 characters
    print(sub["answers_selected_text"].value_counts(dropna=False))
    print()

==== W1_QID56
Please indicate which is the best answer to solve the puzzle below.

Puzzle Grid (3x3 Matrix)

Each cell in a 3x3 matrix contains a circle with an arrow pointing in one of four directions (up, down, left, right) and sometimes includes a diagonal or horizontal/vertical line inside the circle. We'll
answers_selected_text
D    1468
A     255
B     176
E     118
C      22
F      18
Name: count, dtype: int64

==== W2_QID38
Normally, which asset described below displays the highest fluctuations over time?
answers_selected_text
Stocks             1897
Bonds                62
Do not know          61
Savings account      35
Name: count, dtype: int64

==== W2_QID41
Considering a long time period (for example 10 or 20 years), which asset described below normally gives the highest return?
answers_selected_text
Stocks             1221
Bonds               570
Do not know         140
Savings account     125
Name: count, dtype: int64

In [154]:
db_questions = (parsed_questions_df[parsed_questions_df["qtype"] == "DB"]
   .drop_duplicates("q_key")
   [["wave", "block_name", "q_key", "qtext"]]
   .sort_values(["wave", "block_name"])
   .reset_index(drop=True))

In [155]:
missing_qIDs = coverage[coverage["n_missing"] > 0]

In [157]:
parsed_questions_df.columns

Index(['pid', 'element', 'block_name', 'block_type', 'wave', 'qID', 'qtext',
       'qtype', 'options', 'settings_selector', 'settings_subSelector',
       'settings_forceResponse', 'answers_selected_position',
       'answers_selected_text', 'q_key', 'is_answerable'],
      dtype='object')

In [160]:
off_forceResponse_df = parsed_questions_df[parsed_questions_df["settings_forceResponse"]=="OFF"]

In [161]:
off_forceResponse_df

,pid,element,block_name,block_type,wave,qID,qtext,qtype,options,settings_selector,settings_subSelector,settings_forceResponse,answers_selected_position,answers_selected_text,q_key,is_answerable
17,574,1,Personality,Standard,1,QID29,Below are 24 different values that people rate...,Matrix,None,Likert,SingleAnswer,OFF,"[5, 5, 6, 7, 8, 9, 9, 9, 8, 8, 8, 7, 5, 6, 9, ...","[Quite Important to me 5, Quite Important to m...",W1_QID29,True
27,574,2,Cognitive tests,Standard,1,QID56,Please indicate which is the best answer to so...,MC,"[A, B, C, D, E, F]",SAHR,TX,OFF,4,D,W1_QID56,True
93,574,6,Cognitive tests,Standard,2,QID38,"Normally, which asset described below displays...",MC,"[Savings account, Stocks, Bonds, Do not know]",SAVR,TX,OFF,2,Stocks,W2_QID38,True
95,574,6,Cognitive tests,Standard,2,QID40,When an investor spreads their money among dif...,MC,"[Increases, Decreases, Stays the same, Do not ...",SAVR,TX,OFF,2,Decreases,W2_QID40,True
96,574,6,Cognitive tests,Standard,2,QID41,Considering a long time period (for example 10...,MC,"[Savings account, Stocks, Bonds, Do not know]",SAVR,TX,OFF,2,Stocks,W2_QID41,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485539,1029,9,Economic preferences,Standard,2,QID271,We are now interested in what you were thinkin...,TE,None,FORM,None,OFF,None,None,W2_QID271,True
485540,1029,9,Economic preferences,Standard,2,QID272,"Second, please list the thoughts you had when ...",TE,None,FORM,None,OFF,None,None,W2_QID272,True
485541,1029,10,Personality,Standard,3,QID28,Here are a number of characteristics that may ...,Matrix,None,Likert,SingleAnswer,OFF,"[7, 6, 6, 7, 6, 4, 6, 4, 4, 2]","[Definitely true, True, True, Definitely true,...",W3_QID28,True
485574,1029,11,Cognitive tests,Standard,3,QID221,Imagine you see a number of cards from a set o...,MC,"[A, F, 3, 7]",MAHR,TX,OFF,"[1, 3]","[A, 3]",W3_QID221,True
485576,1029,12,Economic preferences,Standard,3,QID275,We are now interested in what you were thinkin...,TE,None,FORM,None,OFF,None,None,W3_QID275,True

In [165]:
coverage["q_key"] = "W" + coverage["wave"].astype(str) + "_" + coverage["qID"]
missing_keys = coverage.loc[coverage["n_missing"] > 0, "q_key"]

In [166]:
missing_keys

16      W1_QID52
20      W1_QID56
89      W2_QID38
92      W2_QID41
119    W2_QID271
120    W2_QID272
Name: q_key, dtype: object

In [168]:
coverage_with_off_forceResponse = off_forceResponse_df[off_forceResponse_df["q_key"].isin(missing_keys)]

In [170]:
coverage_with_off_forceResponse["q_key"].value_counts()

q_key
W1_QID56     2057
W2_QID41     2056
W2_QID38     2055
W2_QID271    2054
W2_QID272    2028
Name: count, dtype: int64

In [171]:
parsed_questions_df["is_answerable"] = parsed_questions_df["qtype"] != "DB"

In [176]:
non_answerable_df = parsed_questions_df[parsed_questions_df["qtype"] == "DB"]

In [178]:
non_answerable_df["q_key"].value_counts()

q_key
W1_QID260    2058
W1_QID262    2058
W1_QID241    2058
W1_QID62     2058
W1_QID73     2058
W1_QID265    2058
W1_QID266    2058
W2_QID285    2058
W2_QID241    2058
W2_QID242    2058
W2_QID243    2058
W2_QID249    2058
W3_QID127    2058
W3_QID240    2058
W4_QID8      2058
Name: count, dtype: int64